"""Pine Script v6 builtin symbol catalog — 56 entries total across PI + PG."""

BUILTINS = {
    "na":             {"category": "core",      "returns": "bool",   "description": "not-a-number check"},
    "nz":             {"category": "core",      "returns": "float",  "description": "replace na with default"},
    "indicator":      {"category": "declaration","returns": "void",  "description": "declare indicator"},
    "strategy":       {"category": "declaration","returns": "void",  "description": "declare strategy"},
    "int":            {"category": "type",      "returns": "type",   "description": "integer type"},
    "plot":           {"category": "output",    "returns": "plot",   "description": "plot a series"},
    "bgcolor":        {"category": "output",    "returns": "void",   "description": "set background color"},
    "hline":          {"category": "output",    "returns": "hline",  "description": "draw horizontal line"},
    "fill":           {"category": "output",    "returns": "fill",   "description": "fill between plots"},
    "alert":          {"category": "output",    "returns": "void",   "description": "create alert condition"},
    "input.symbol":   {"category": "input",     "returns": "string", "description": "symbol input"},
    "input.string":   {"category": "input",     "returns": "string", "description": "string input"},
    "input.int":      {"category": "input",     "returns": "int",    "description": "integer input"},
    "input.float":    {"category": "input",     "returns": "float",  "description": "float input"},
    "input.bool":     {"category": "input",     "returns": "bool",   "description": "boolean input"},
    "MarketData.new": {"category": "type",      "returns": "object", "description": "create MarketData instance"},
    "ta.rsi":         {"category": "indicator", "returns": "float",  "description": "relative strength index"},
    "ta.sma":         {"category": "indicator", "returns": "float",  "description": "simple moving average"},
    "ta.ema":         {"category": "indicator", "returns": "float",  "description": "exponential moving average"},
    "ta.macd":        {"category": "indicator", "returns": "float",  "description": "MACD oscillator"},
    "ta.stoch":       {"category": "indicator", "returns": "float",  "description": "stochastic oscillator"},
    "ta.atr":         {"category": "indicator", "returns": "float",  "description": "average true range"},
    "ta.dmi":         {"category": "indicator", "returns": "float",  "description": "directional movement index"},
    "ta.supertrend":  {"category": "indicator", "returns": "float",  "description": "supertrend indicator"},
    "ta.highest":     {"category": "indicator", "returns": "float",  "description": "highest value over period"},
    "ta.lowest":      {"category": "indicator", "returns": "float",  "description": "lowest value over period"},
    "ta.correlation": {"category": "indicator", "returns": "float",  "description": "Pearson correlation"},
    "ta.rising":      {"category": "indicator", "returns": "bool",   "description": "check if rising"},
    "ta.stdev":       {"category": "indicator", "returns": "float",  "description": "standard deviation"},
    "math.abs":       {"category": "math",      "returns": "float",  "description": "absolute value"},
    "math.max":       {"category": "math",      "returns": "float",  "description": "maximum of two values"},
    "math.min":       {"category": "math",      "returns": "float",  "description": "minimum of two values"},
    "math.round":     {"category": "math",      "returns": "float",  "description": "round to nearest integer"},
    "math.sqrt":      {"category": "math",      "returns": "float",  "description": "square root"},
    "math.floor":     {"category": "math",      "returns": "int",    "description": "floor function"},
    "math.log":       {"category": "math",      "returns": "float",  "description": "natural logarithm"},
    "math.sum":       {"category": "math",      "returns": "float",  "description": "sum over period"},
    "str.contains":   {"category": "string",    "returns": "bool",   "description": "check if string contains substring"},
    "str.tostring":   {"category": "string",    "returns": "string", "description": "convert value to string"},
    "str.format":     {"category": "string",    "returns": "string", "description": "format string with arguments"},
    "color.new":      {"category": "color",     "returns": "color",  "description": "create color with alpha"},
    "color.rgb":      {"category": "color",     "returns": "color",  "description": "create color from RGB"},
    "array.from":     {"category": "array",     "returns": "array",  "description": "create array from elements"},
    "array.get":      {"category": "array",     "returns": "any",    "description": "get element at index"},
    "array.set":      {"category": "array",     "returns": "void",   "description": "set element at index"},
    "array.size":     {"category": "array",     "returns": "int",    "description": "array length"},
    "array.includes": {"category": "array",     "returns": "bool",   "description": "check if array contains value"},
    "array.new_float": {"category": "array",    "returns": "array",  "description": "create float array"},
    "array.new_int":  {"category": "array",     "returns": "array",  "description": "create int array"},
    "request.security": {"category": "request", "returns": "any",    "description": "request data from symbol"},
    "request.financial": {"category": "request","returns": "float",  "description": "request financial data"},
    "table.new":      {"category": "table",     "returns": "table",  "description": "create new table"},
    "table.cell":     {"category": "table",     "returns": "void",   "description": "set table cell content"},
    "table.clear":    {"category": "table",     "returns": "void",   "description": "clear table"},
    "strategy.entry": {"category": "strategy",  "returns": "void",   "description": "enter a position"},
    "strategy.exit":  {"category": "strategy",  "returns": "void",   "description": "exit a position"},
}
